// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191120194320_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Activities", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgeRange");

                    b.Property<string>("Description");

                    b.Property<string>("Duration");

                    b.Property<int>("ScheduleId");

                    b.Property<int>("Score");

                    b.HasKey("ActivitiesId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Activities");

                    b.HasData(
                        new { ActivitiesId = 1, AgeRange = "3", Description = "Play Groups", Duration = "60", ScheduleId = 1, Score = 150 },
                        new { ActivitiesId = 2, AgeRange = "3", Description = "Read to Your Child", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 3, AgeRange = "3", Description = "Matching Games", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 4, AgeRange = "3", Description = "Ascend and Descend Stairs", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 5, AgeRange = "3", Description = "Play Outside", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 6, AgeRange = "3", Description = "Go to the Park or a Hiking Trail", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 7, AgeRange = "4", Description = "Play Make Believe", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 8, AgeRange = "4", Description = "Childs Choice Snack Time", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 9, AgeRange = "4", Description = "Read with your child", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 10, AgeRange = "4", Description = "Outdoor Games (Tag, Duck Duck Goose)", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 11, AgeRange = "4", Description = "Dance with your child", Duration = "15", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 12, AgeRange = "5", Description = "Dance with your child", Duration = "15", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 13, AgeRange = "5", Description = "Educate: Address and Phone Number", Duration = "5", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 14, AgeRange = "5", Description = "Encourage your child to read to you through pictures", Duration = "25", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 15, AgeRange = "5", Description = "Petting Zoo", Duration = "60", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 16, AgeRange = "5", Description = "Art Projects", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 17, AgeRange = "5", Description = "Scavenger Hunt", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 18, AgeRange = "5", Description = "Ride A Bicycle", Duration = "20", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 19, AgeRange = "5", Description = "Visit the Library", Duration = "60", ScheduleId = 1, Score = 100 },
                        new { ActivitiesId = 20, AgeRange = "5", Description = "Educate: Days of the Week", Duration = "5", ScheduleId = 1, Score = 100 }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Milestones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgeId");

                    b.Property<string>("Milestone");

                    b.Property<string>("SkillAssoc");

                    b.HasKey("Id");

                    b.ToTable("Milestones");

                    b.HasData(
                        new { Id = 1, AgeId = "3", Milestone = "Follows Instructions with 2 or 3 steps", SkillAssoc = "Speech" },
                        new { Id = 2, AgeId = "3", Milestone = "Can name most familiar things", SkillAssoc = "Speech" },
                        new { Id = 3, AgeId = "3", Milestone = "Understands words like 'in,' 'on,' and 'under'", SkillAssoc = "Speech" },
                        new { Id = 4, AgeId = "3", Milestone = "Says first name, age, sex", SkillAssoc = "Speech" },
                        new { Id = 5, AgeId = "3", Milestone = "Names a Friend", SkillAssoc = "Speech" },
                        new { Id = 6, AgeId = "3", Milestone = "Says words like 'I,' 'me,' 'we,' and 'you' and some plurals (cars, dogs, cats)", SkillAssoc = "Speech" },
                        new { Id = 7, AgeId = "3", Milestone = "Talks well enough for strangers to understand most of the time", SkillAssoc = "Speech" },
                        new { Id = 8, AgeId = "3", Milestone = "Carries on a conversation using 2 to 3 sentences", SkillAssoc = "Speech" },
                        new { Id = 9, AgeId = "4", Milestone = "Knows some basic rules of grammar, such as correctly using 'he' and 'she'", SkillAssoc = "Speech" },
                        new { Id = 10, AgeId = "4", Milestone = "Sings a song or poem from memory such as the 'itsy Bitsy Spider' or the 'Wheels on the Bus'", SkillAssoc = "Speech" },
                        new { Id = 11, AgeId = "4", Milestone = "Tells Stories", SkillAssoc = "Speech" },
                        new { Id = 12, AgeId = "4", Milestone = "Can say first and last name", SkillAssoc = "Speech" },
                        new { Id = 13, AgeId = "5", Milestone = "Speaks very clearly", SkillAssoc = "Speech" },
                        new { Id = 14, AgeId = "5", Milestone = "Tells a simple story using full sentences", SkillAssoc = "Speech" },
                        new { Id = 15, AgeId = "5", Milestone = "Uses future tense; for example, 'Grandma will be here'", SkillAssoc = "Speech" },
                        new { Id = 16, AgeId = "5", Milestone = "Says full name and address", SkillAssoc = "Speech" },
                        new { Id = 17, AgeId = "3", Milestone = "Can work toys with buttons, levers and moving parts", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 18, AgeId = "3", Milestone = "Turns book pages one at a time", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 19, AgeId = "3", Milestone = "Screws and unscrews jar lids or turns door handles", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 20, AgeId = "3", Milestone = "Plays make-believe with dolls, animals, and people", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 21, AgeId = "3", Milestone = "Understands what 'two' means", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 22, AgeId = "3", Milestone = "Copies a circle with pencil or crayon", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 23, AgeId = "4", Milestone = "Names some colors and some numbers", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 24, AgeId = "4", Milestone = "Starts to understand time", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 25, AgeId = "4", Milestone = "Remembers parts of a story", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 26, AgeId = "4", Milestone = "Understands the idea of 'same' and 'different'", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 27, AgeId = "4", Milestone = "Draws a person with 2 to 4 body parts", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 28, AgeId = "4", Milestone = "Uses scissors", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 29, AgeId = "4", Milestone = "Stars to copy some capital letters", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 30, AgeId = "4", Milestone = "Starts to copy some capital letters", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 31, AgeId = "4", Milestone = "Plays board or card games", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 32, AgeId = "4", Milestone = "Tells you what he or she thinks is going to happen next in a book", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 33, AgeId = "5", Milestone = "Names some colors and some numbers", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 34, AgeId = "5", Milestone = "Count 10 or more things", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 35, AgeId = "5", Milestone = "Can draw a person with at least 6 body parts", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 36, AgeId = "5", Milestone = "Can print some letters or numbers", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 37, AgeId = "5", Milestone = "Copies a triangle and other geometric shapes", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 38, AgeId = "5", Milestone = "Knows about things used everyday, like money and food", SkillAssoc = "Cognitive Functionality" },
                        new { Id = 39, AgeId = "3", Milestone = "Climbs well", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 40, AgeId = "3", Milestone = "Runs Easily", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 41, AgeId = "3", Milestone = "Pedals a Tricycle (3-Wheel Bike)", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 42, AgeId = "3", Milestone = "Walks up and down stairs, one foot on each step", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 43, AgeId = "4", Milestone = "Hops and stands on one foot up to 2 seconds", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 44, AgeId = "4", Milestone = "Catches a bounced ball most of the time", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 45, AgeId = "4", Milestone = "Pours, cuts with supervision and mashes own food", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 46, AgeId = "5", Milestone = "Stands on one foot for 10 seconds or longer", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 47, AgeId = "5", Milestone = "Hops, may be able to skip", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 48, AgeId = "5", Milestone = "Can do a somersault", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 49, AgeId = "5", Milestone = "Uses a fork or spoon and sometimes a table knife", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 50, AgeId = "5", Milestone = "Can use the toilet on his or her own", SkillAssoc = "Fine/Gross Motor Skills" },
                        new { Id = 51, AgeId = "5", Milestone = "Swings and climbs", SkillAssoc = "Fine/Gross Motor Skills" }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new { ScheduleId = 1 }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Skills", b =>
                {
                    b.Property<int>("SkillsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgeId");

                    b.Property<string>("DescriptionId");

                    b.Property<string>("SkillName");

                    b.HasKey("SkillsId");

                    b.ToTable("Skills");

                    b.HasData(
                        new { SkillsId = 1, AgeId = "3-5", DescriptionId = "Children are born ready to learn a language, but they need to learn the language or languages that their family and environment use. Learning a language takes time, and children vary in how quickly they master milestones in language and speech development. Typically developing children may have trouble with some sounds, words, and sentences while they are learning. However, most children can use language easily around 5 years of age.", SkillName = "Speech" },
                        new { SkillsId = 2, AgeId = "3-5", DescriptionId = "This is the ability to use small muscles (fine motor), particularly in the hands, and large muscles (gross motor) in the body. Babies use fine motor skills to grasp objects. Toddlers and preschoolers use them to do things like hold utensils, work with objects, and draw. Babies use gross motor skills to sit up, roll over, and begin to walk. Older kids use them to do things like jump, run, and climb stairs.", SkillName = "Fine/Gross Motor Skills" },
                        new { SkillsId = 3, AgeId = "3-5", DescriptionId = "Children are born ready to learn, and have many skills to learn over many years. They depend on parents, family members, and other caregivers as their first teachers to develop the right skills to become independent and lead healthy and successful lives. How the brain grows is strongly affected by the child’s experiences with other people and the world. Nurturing care for the mind is critical for brain growth. Children grow and learn best in a safe environment where they are protected from neglect and from extreme or chronic stress. External with plenty of opportunities to play and explore.", SkillName = "Cognitive Functionality" }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Activities", b =>
                {
                    b.HasOne("FinalProject.Models.Schedule", "Schedule")
                        .WithMany("Activities")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
