// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191120152918_second-migration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Activities", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgeRange");

                    b.Property<string>("Description");

                    b.Property<string>("Duration");

                    b.Property<int>("ScheduleId");

                    b.Property<int>("Score");

                    b.Property<string>("Title");

                    b.HasKey("ActivitiesId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Activities");

                    b.HasData(
                        new { ActivitiesId = 1, AgeRange = "3-5", Description = "Description", Duration = "10", ScheduleId = 1, Score = 100, Title = "title 1" },
                        new { ActivitiesId = 2, AgeRange = "3-5", Description = "secondDescription", Duration = "33", ScheduleId = 1, Score = 800, Title = "title 2" }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new { ScheduleId = 1 }
                    );
                });

            modelBuilder.Entity("FinalProject.Models.Activities", b =>
                {
                    b.HasOne("FinalProject.Models.Schedule", "Schedule")
                        .WithMany("Activities")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
